import { FONT } from "./lib/theme"

const styles: Record<string, React.CSSProperties> = {
  container: {
    width: 420,
    height: 520,
    maxHeight: 520,
    padding: "16px 16px 12px",
    fontFamily: FONT,
    background: "var(--bg)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxSizing: "border-box",
    color: "var(--text)",
  },
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
  },
  title: {
    fontSize: 18,
    fontWeight: 400,
    margin: 0,
    color: "var(--text)",
    letterSpacing: "-0.02em",
  },
  titleAccent: {
    color: "var(--accent)",
    fontWeight: 300,
  },
  titleActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  // shared base for 28x28 icon buttons
  iconBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: 4,
    padding: 0,
  } as React.CSSProperties,
  iconBtnDefault: {
    background: "transparent",
    border: "1px solid var(--border)",
    cursor: "pointer",
    color: "var(--text-dim)",
    fontFamily: FONT,
  } as React.CSSProperties,
  iconBtnActive: {
    background: "var(--accent-dim)",
    border: "1px solid var(--accent)",
    cursor: "pointer",
    color: "var(--accent)",
    fontFamily: FONT,
  } as React.CSSProperties,

  themeBtn: {
    fontSize: 15,
    lineHeight: 1,
  },
  githubBtn: {
    color: "var(--text-dim)",
    border: "1px solid var(--border)",
  },
  settingsBtn: {
    fontSize: 14,
    lineHeight: 1,
  },
  settingsBtnOn: {
    fontSize: 14,
    lineHeight: 1,
  },
  settingsPage: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    minHeight: 0,
    padding: "8px 0",
  },
  settingsGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  settingsLabel: {
    fontSize: 13,
    color: "var(--text)",
    fontWeight: 400,
  },
  settingsHint: {
    fontSize: 12,
    color: "var(--text-dim)",
    lineHeight: 1.5,
  },
  stepper: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    marginTop: 4,
  },
  stepperBtn: {
    width: 34,
    height: 34,
    padding: 0,
    fontSize: 17,
    fontFamily: FONT,
    lineHeight: "34px",
    textAlign: "center",
    background: "var(--surface)",
    color: "var(--text)",
    border: "1px solid var(--border)",
    cursor: "pointer",
    outline: "none",
  },
  stepperValue: {
    display: "flex",
    alignItems: "center",
    borderTop: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
  },
  fieldError: {
    fontSize: 12,
    color: "var(--red)",
    marginTop: 2,
  },
  stepperInput: {
    width: 60,
    height: 32,
    padding: 0,
    textAlign: "center",
    fontSize: 15,
    fontFamily: FONT,
    background: "var(--surface)",
    color: "var(--accent)",
    border: "none",
    outline: "none",
  },
  compactOn: {
    padding: "3px 8px",
    fontSize: 13,
    lineHeight: 1,
    background: "var(--accent-dim)",
    border: "1px solid var(--accent)",
    borderRadius: 3,
    cursor: "pointer",
    color: "var(--accent)",
    fontFamily: FONT,
  },
  compactOff: {
    padding: "3px 8px",
    fontSize: 13,
    lineHeight: 1,
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 3,
    cursor: "pointer",
    color: "var(--text-dim)",
    fontFamily: FONT,
  },
  inputRow: {
    display: "flex",
    gap: 8,
  },
  inputWrap: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    paddingLeft: 10,
  },
  inputPrompt: {
    color: "var(--accent)",
    fontSize: 14,
    marginRight: 8,
    userSelect: "none",
  },
  input: {
    flex: 1,
    padding: "9px 10px 9px 0",
    fontSize: 14,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text)",
    fontFamily: FONT,
  },
  btn: {
    padding: "8px 22px",
    fontSize: 14,
    fontWeight: 400,
    background: "var(--accent)",
    color: "var(--btn-text)",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: FONT,
    letterSpacing: "0.02em",
  },
  btnLoading: {
    display: "inline-flex",
    alignItems: "center",
  },
  clearBtn: {
    padding: "6px 10px",
    fontSize: 17,
    lineHeight: "20px",
    background: "transparent",
    color: "var(--text-dim)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: FONT,
  },
  loading: {
    padding: "32px 0 20px",
  },
  error: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 12px",
    background: "var(--red-bg)",
    borderRadius: 4,
    border: "1px solid var(--red-bg)",
  },
  errorText: {
    color: "var(--red)",
    fontSize: 13,
    flex: 1,
  },
  errorClose: {
    padding: 0,
    width: 20,
    height: 20,
    fontSize: 16,
    lineHeight: "20px",
    textAlign: "center",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--red)",
    flexShrink: 0,
    fontFamily: FONT,
  },
  summaryRow: {
    flexShrink: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  summaryRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  checkWrap: {
    display: "flex",
    alignItems: "center",
  },
  checkbox: {
    width: 15,
    height: 15,
    accentColor: "var(--accent)",
    cursor: "pointer",
    margin: 0,
  },
  clearSelBtn: {
    padding: "2px 8px",
    fontSize: 11,
    fontFamily: FONT,
    background: "var(--surface)",
    color: "var(--text-dim)",
    border: "1px solid var(--border)",
    borderRadius: 3,
    cursor: "pointer",
  },
  exportBar: {
    flexShrink: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    padding: "5px 0",
  },
  exportBtn: {
    padding: "5px 14px",
    fontSize: 12,
    fontWeight: 400,
    fontFamily: FONT,
    background: "var(--accent)",
    color: "var(--btn-text)",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
  },
  exportHint: {
    fontSize: 12,
    color: "var(--text-dim)",
    fontFamily: FONT,
  },
  toggleGroup: {
    display: "flex",
    gap: 0,
    marginTop: 4,
  },
  toggleOn: {
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: FONT,
    background: "var(--accent-dim)",
    color: "var(--accent)",
    border: "1px solid var(--accent)",
    cursor: "pointer",
    outline: "none",
  },
  toggleOff: {
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: FONT,
    background: "var(--surface)",
    color: "var(--text-dim)",
    border: "1px solid var(--border)",
    cursor: "pointer",
    outline: "none",
  },
  settingsSection: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  summary: {
    fontSize: 13,
    color: "var(--text-dim)",
  },
  empty: {
    fontSize: 13,
    color: "var(--text-dim)",
  },
  cached: {
    fontSize: 11,
    color: "var(--text-muted)",
    fontStyle: "italic",
  },
  countBadge: {
    fontSize: 12,
    fontWeight: 400,
    color: "var(--accent)",
    background: "var(--accent-dim)",
    padding: "2px 8px",
    borderRadius: 3,
    minWidth: 18,
    textAlign: "center",
  },
  onboarding: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: "0 12px",
    minHeight: 0,
    textAlign: "center",
  },
  onboardTitle: {
    fontSize: 15,
    fontWeight: 400,
    color: "var(--text)",
    letterSpacing: "0.02em",
  },
  onboardDesc: {
    fontSize: 13,
    color: "var(--text-dim)",
    lineHeight: 1.6,
    maxWidth: 300,
  },
  examplesGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    maxWidth: 320,
  },
  exampleChip: {
    padding: "5px 12px",
    fontSize: 12,
    fontFamily: FONT,
    background: "var(--surface)",
    color: "var(--text-dim)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    cursor: "pointer",
  },
  results: {
    flex: 1,
    overflowY: "auto",
    minHeight: 0,
    paddingRight: 8,
  },
  card: {
    flexShrink: 0,
    height: 210,
    display: "flex",
    flexDirection: "column",
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  },
  cardHeader: {
    flexShrink: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "7px 10px",
    background: "var(--raised)",
    borderBottom: "1px solid var(--border)",
  },
  cardHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  matchedBy: {
    fontSize: 12,
    color: "var(--text-dim)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: {
    fontSize: 12,
    fontWeight: 400,
    color: "var(--text)",
    background: "var(--border)",
    padding: "2px 8px",
    borderRadius: 3,
    letterSpacing: "0.03em",
  },
  idx: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFeatureSettings: "'tnum'",
    fontVariantNumeric: "tabular-nums",
  },
  cardActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  expandBtn: {
    padding: "2px 8px",
    fontSize: 14,
    lineHeight: 1,
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 3,
    cursor: "pointer",
    color: "var(--text-dim)",
    fontFamily: FONT,
  },
  backBtn: {
    padding: "4px 10px",
    fontSize: 16,
    lineHeight: 1,
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 3,
    cursor: "pointer",
    color: "var(--text)",
    fontFamily: FONT,
  },
  detail: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
  },
  detailHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  detailCode: {
    flex: 1,
    margin: 0,
    padding: "10px 12px",
    fontSize: 13,
    fontFamily: FONT,
    overflow: "auto",
    lineHeight: 1.6,
    minHeight: 0,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    whiteSpace: "pre",
    color: "var(--text)",
  },
  code: {
    flex: 1,
    margin: 0,
    padding: "10px 12px",
    fontSize: 13,
    fontFamily: FONT,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowY: "auto",
    lineHeight: 1.6,
    minHeight: 0,
    color: "var(--text)",
    background: "var(--surface)",
  },
  historyWrap: {
    position: "relative" as const,
    width: "100%",
  },
  historyDropdown: {
    position: "absolute" as const,
    top: "100%",
    left: 0,
    right: 0,
    width: "100%",
    maxHeight: 210,
    overflowY: "auto" as const,
    marginTop: 2,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    zIndex: 10,
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
  },
  historyItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "6px 10px",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    borderBottom: "1px solid var(--border)",
    color: "inherit",
    fontFamily: FONT,
    textAlign: "left" as const,
    gap: 8,
  } as React.CSSProperties,
  historyItemLast: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "6px 10px",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    color: "inherit",
    fontFamily: FONT,
    textAlign: "left" as const,
    gap: 8,
  } as React.CSSProperties,
  historyContent: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 1,
    overflow: "hidden",
  },
  historySelector: {
    fontSize: 13,
    fontFamily: FONT,
    color: "var(--accent)",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  historyUrl: {
    fontSize: 11,
    fontFamily: FONT,
    color: "var(--text-dim)",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  historyDelete: {
    flexShrink: 0,
    width: 22,
    height: 22,
    padding: 0,
    fontSize: 13,
    lineHeight: "22px",
    textAlign: "center" as const,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    fontFamily: FONT,
    borderRadius: 3,
  },
  historyCurrent: {
    borderLeft: "3px solid var(--accent)",
  },
  historyCurrentDot: {
    display: "inline-block",
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--accent)",
    flexShrink: 0,
    marginRight: 2,
  },
  historyShowMore: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: "5px 10px",
    fontSize: 11,
    fontFamily: FONT,
    background: "var(--raised)",
    color: "var(--text-dim)",
    border: "none",
    cursor: "pointer",
  },
};

export default styles
